# Generated by Django 6.0 on 2025-12-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='หัวข้อแบนเนอร์')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='รูปภาพแบนเนอร์')),
                ('link', models.URLField(blank=True, verbose_name='ลิงก์ (ถ้ามี)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('image', models.ImageField(upload_to='products/', verbose_name='รูปสินค้า')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
            ],
        ),
    ]
